name: faabul_color_conversion
description: Flutter extensions on String to parse web colors and on Color to produce web color String.
version: 1.0.0
homepage: https://github.com/yomio/faabul_color_conversion
repository: https://github.com/yomio/faabul_color_conversion.git
issue_tracker: https://github.com/yomio/faabul_color_conversion/issues
topics:
 - color
 - parser
 - extension

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
